### ISSUE TITLE
schema dbmirror2 does not exist

### ISSUE THREAD

**Issue by verl-tech** [acoustid/mbslave#15]
New install using:  "pipx install git+https://github.com/acoustid/mbslave.git"

database imports fine using: "mbslave init --create-database"

running command "mbslave sync" fails with the following: 

INFO:mbslave.replication:Downloading https://metabrainz.org/api/musicbrainz/replication-170231-v2.tar.bz2?token=***
INFO:mbslave.replication:Packet was produced at 2024-08-21 01:05:40.896471+00
Traceback (most recent call last):
  File "/root/.local/bin/mbslave", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pipx/venvs/mbslave/lib64/python3.9/site-packages/mbslave/replication.py", line 801, in main
    args.func(config, args)
  File "/root/.local/share/pipx/venvs/mbslave/lib64/python3.9/site-packages/mbslave/replication.py", line 516, in mbslave_sync_main
    process_tar(packet, db, config, ignored_schemas, ignored_tables, schema_seq, replication_seq, hook)
  File "/root/.local/share/pipx/venvs/mbslave/lib64/python3.9/site-packages/mbslave/replication.py", line 460, in process_tar
    importer.load_pending_data(member_file)
  File "/root/.local/share/pipx/venvs/mbslave/lib64/python3.9/site-packages/mbslave/replication.py", line 355, in load_pending_data
    cursor.execute('TRUNCATE dbmirror2.pending_data')
psycopg2.errors.InvalidSchemaName: schema "dbmirror2" does not exist

**Comment by lalinsky** [comment]
I've just merged https://github.com/acoustid/mbslave/pull/8 which should fix this.
